// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/ibm/starter-kit-operator/pkg/apis/devx/v1alpha1.StarterKit":       schema_pkg_apis_devx_v1alpha1_StarterKit(ref),
		"github.com/ibm/starter-kit-operator/pkg/apis/devx/v1alpha1.StarterKitSpec":   schema_pkg_apis_devx_v1alpha1_StarterKitSpec(ref),
		"github.com/ibm/starter-kit-operator/pkg/apis/devx/v1alpha1.StarterKitStatus": schema_pkg_apis_devx_v1alpha1_StarterKitStatus(ref),
	}
}

func schema_pkg_apis_devx_v1alpha1_StarterKit(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StarterKit is the Schema for the starterkits API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/ibm/starter-kit-operator/pkg/apis/devx/v1alpha1.StarterKitSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/ibm/starter-kit-operator/pkg/apis/devx/v1alpha1.StarterKitStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/ibm/starter-kit-operator/pkg/apis/devx/v1alpha1.StarterKitSpec", "github.com/ibm/starter-kit-operator/pkg/apis/devx/v1alpha1.StarterKitStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_devx_v1alpha1_StarterKitSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StarterKitSpec defines the desired state of StarterKit",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_devx_v1alpha1_StarterKitStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StarterKitStatus defines the observed state of StarterKit",
				Type:        []string{"object"},
			},
		},
	}
}
