kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: authors
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authors
        version: v1
    spec:
      containers:
      - name: authors
        image: docker-registry.default.svc:5000/swagger/authors:latest
        ports:
        - containerPort: 3001
        livenessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:3001/"]
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:3001/health | grep -q authors"]
          initialDelaySeconds: 40
      restartPolicy: Always
