apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: starter-kit-operator
  name: starter-kit-operator-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: starter-kit-operator
