swagger: "2.0"
info:
  title: Starter Kit Operator
  description: API description in Markdown.
  version: 1.0.0
host: my-cluster-host
basePath: /apis/devx.ibm.com/v1alpha1
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
security:
  - Bearer: []
schemes:
  - https
paths:
  /starterkits:
    get:
      summary: Return all starter kits located in all namespaces.
      tags:
        - Starter Kit Operations
      description: Returns a StarterKitList.
      produces:
        - application/json
      responses:
        200:
          description: OK
        403:
          description: Unauthorized
  /namespaces/{namespace}/starterkits:
    get:
      summary: Return all installed starter kits located in a specific namespace.
      tags:
        - Starter Kit Operations
      description: Returns a StarterKitList.
      parameters:
        - in: path
          name: namespace
          schema:
            type: string
            default: default
          required: true
          description: Namespace where the starter kit is located.
      produces:
        - application/json
      responses:
        200:
          description: OK
        403:
          description: Unauthorized
    post:
      summary: Creates a starter kit.
      tags:
        - Starter Kit Operations
      consumes:
        - application/yaml
      parameters:
        - in: path
          name: namespace
          schema:
            type: string
            default: default
          required: true
          description: Namespace where the starter kit will be located.
        - in: body
          name: body
          required: true
          schema:
            type: string  
      produces:
        - application/json
      responses:
        200:
          description: OK
        403:
          description: Unauthorized
  /namespaces/{namespace}/starterkits/{name}:
    get:
      summary: Returns starter kit information.
      tags:
        - Starter Kit Operations
      description: Returns details about a starter kit.
      parameters:
        - in: path
          name: namespace
          schema:
            type: string
            default: default
          required: true
          description: Namespace where the starter kit is located.
        - in: path
          name: name
          schema:
            type: string
            default: java-spring-app
          required: true
          description: The name of the starter kit.
      produces:
        - application/json
      responses:
        200:
          description: OK
        403:
          description: Unauthorized
