swagger: "2.0"
info:
  title: Starter Kit Operator
  description: Perform operations on Starter Kits.
  version: 1.0.0
host: kubernetes.default.svc.cluster.local
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
security:
  - Bearer: []
schemes:
  - https
paths:
  /apis/devx.ibm.com/v1alpha1/starterkits:
    get:
      summary: Return all starter kits located in all namespaces.
      tags:
        - Starter Kit Operations
      description: Returns a StarterKitList.
      produces:
        - application/json
      responses:
        200:
          description: OK
        403:
          description: Unauthorized
  /apis/devx.ibm.com/v1alpha1/namespaces/{namespace}/starterkits:
    get:
      summary: Return all installed starter kits located in a specific namespace.
      tags:
        - Starter Kit Operations
      description: Returns a StarterKitList.
      parameters:
        - in: path
          name: namespace
          type: string
          required: true
          description: Namespace where the starter kit is located.
      produces:
        - application/json
      responses:
        200:
          description: OK
        403:
          description: Unauthorized
    post:
      summary: Creates a starter kit.
      tags:
        - Starter Kit Operations
      consumes:
        - application/yaml
      parameters:
        - in: path
          name: namespace
          type: string
          required: true
          description: Namespace where the starter kit will be located.
        - in: body
          name: body
          description: Stringified yaml matching starter kit kind.
          required: true
          schema:
            type: string
      produces:
        - application/json
      responses:
        200:
          description: OK
        403:
          description: Unauthorized
  /apis/devx.ibm.com/v1alpha1/namespaces/{namespace}/starterkits/{name}:
    get:
      summary: Returns starter kit information.
      tags:
        - Starter Kit Operations
      description: Returns details about a starter kit.
      parameters:
        - in: path
          name: namespace
          type: string
          required: true
          description: Namespace where the starter kit is located.
        - in: path
          name: name
          type: string
          required: true
          description: The name of the starter kit.
      produces:
        - application/json
      responses:
        200:
          description: OK
        403:
          description: Unauthorized
    put:
      summary: Replace the specified StarterKit.
      tags:
        - Starter Kit Operations
      description: Replace the specified StarterKit.
      parameters:
        - in: path
          name: namespace
          type: string
          required: true
          description: Namespace where the starter kit is located.
        - in: path
          name: name
          type: string
          required: true
          description: The name of the starter kit.
        - in: body
          name: body
          required: true
          schema:
            type: string
      produces:
        - application/json
        - application/yaml
      responses:
        200:
          description: OK
        403:
          description: Unauthorized
  /apis/devx.ibm.com/v1alpha1/namespaces/{namespace}/starterkits/{name}/status:
    get:
      summary: read status of the specified StarterKit.
      tags:
        - Starter Kit Operations
      description: read status of the specified StarterKit.
      parameters:
        - in: path
          name: namespace
          type: string
          required: true
          description: Namespace where the starter kit is located.
        - in: path
          name: name
          type: string
          required: true
          description: The name of the starter kit.
      produces:
        - application/json
      responses:
        200:
          description: OK
        403:
          description: Unauthorized
  /api/v1/secrets?labelSelector=devx:
    get:
      summary: list or watch objects of kind Secret
      tags:
        - core_v1
      description: list or watch objects of kind Secret
      produces:
        - application/json
        - application/yaml
        - application/vnd.kubernetes.protobuf
        - application/json;stream=watch
        - application/vnd.kubernetes.protobuf;stream=watch
      responses:
        200:
          description: OK
        401:
          description: Unauthorized

