// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetAPIV1SecretsLabelSelectorDevxParams creates a new GetAPIV1SecretsLabelSelectorDevxParams object
// no default values defined in spec.
func NewGetAPIV1SecretsLabelSelectorDevxParams() GetAPIV1SecretsLabelSelectorDevxParams {

	return GetAPIV1SecretsLabelSelectorDevxParams{}
}

// GetAPIV1SecretsLabelSelectorDevxParams contains all the bound params for the get API v1 secrets label selector devx operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetAPIV1SecretsLabelSelectorDevx
type GetAPIV1SecretsLabelSelectorDevxParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAPIV1SecretsLabelSelectorDevxParams() beforehand.
func (o *GetAPIV1SecretsLabelSelectorDevxParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
