// Code generated by go-swagger; DO NOT EDIT.

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAPIV1SecretsLabelSelectorDevxOKCode is the HTTP code returned for type GetAPIV1SecretsLabelSelectorDevxOK
const GetAPIV1SecretsLabelSelectorDevxOKCode int = 200

/*GetAPIV1SecretsLabelSelectorDevxOK OK

swagger:response getApiV1SecretsLabelSelectorDevxOK
*/
type GetAPIV1SecretsLabelSelectorDevxOK struct {
}

// NewGetAPIV1SecretsLabelSelectorDevxOK creates GetAPIV1SecretsLabelSelectorDevxOK with default headers values
func NewGetAPIV1SecretsLabelSelectorDevxOK() *GetAPIV1SecretsLabelSelectorDevxOK {

	return &GetAPIV1SecretsLabelSelectorDevxOK{}
}

// WriteResponse to the client
func (o *GetAPIV1SecretsLabelSelectorDevxOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetAPIV1SecretsLabelSelectorDevxUnauthorizedCode is the HTTP code returned for type GetAPIV1SecretsLabelSelectorDevxUnauthorized
const GetAPIV1SecretsLabelSelectorDevxUnauthorizedCode int = 401

/*GetAPIV1SecretsLabelSelectorDevxUnauthorized Unauthorized

swagger:response getApiV1SecretsLabelSelectorDevxUnauthorized
*/
type GetAPIV1SecretsLabelSelectorDevxUnauthorized struct {
}

// NewGetAPIV1SecretsLabelSelectorDevxUnauthorized creates GetAPIV1SecretsLabelSelectorDevxUnauthorized with default headers values
func NewGetAPIV1SecretsLabelSelectorDevxUnauthorized() *GetAPIV1SecretsLabelSelectorDevxUnauthorized {

	return &GetAPIV1SecretsLabelSelectorDevxUnauthorized{}
}

// WriteResponse to the client
func (o *GetAPIV1SecretsLabelSelectorDevxUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
