// Code generated by go-swagger; DO NOT EDIT.

package starter_kit_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusOKCode is the HTTP code returned for type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusOK
const GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusOKCode int = 200

/*GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusOK OK

swagger:response getApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusOK
*/
type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusOK struct {
}

// NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusOK creates GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusOK with default headers values
func NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusOK() *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusOK {

	return &GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusOK{}
}

// WriteResponse to the client
func (o *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusForbiddenCode is the HTTP code returned for type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusForbidden
const GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusForbiddenCode int = 403

/*GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusForbidden Unauthorized

swagger:response getApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusForbidden
*/
type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusForbidden struct {
}

// NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusForbidden creates GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusForbidden with default headers values
func NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusForbidden() *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusForbidden {

	return &GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusForbidden{}
}

// WriteResponse to the client
func (o *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
