// Code generated by go-swagger; DO NOT EDIT.

package starter_kit_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetApisDevxIbmComV1alpha1StarterkitsOKCode is the HTTP code returned for type GetApisDevxIbmComV1alpha1StarterkitsOK
const GetApisDevxIbmComV1alpha1StarterkitsOKCode int = 200

/*GetApisDevxIbmComV1alpha1StarterkitsOK OK

swagger:response getApisDevxIbmComV1alpha1StarterkitsOK
*/
type GetApisDevxIbmComV1alpha1StarterkitsOK struct {
}

// NewGetApisDevxIbmComV1alpha1StarterkitsOK creates GetApisDevxIbmComV1alpha1StarterkitsOK with default headers values
func NewGetApisDevxIbmComV1alpha1StarterkitsOK() *GetApisDevxIbmComV1alpha1StarterkitsOK {

	return &GetApisDevxIbmComV1alpha1StarterkitsOK{}
}

// WriteResponse to the client
func (o *GetApisDevxIbmComV1alpha1StarterkitsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetApisDevxIbmComV1alpha1StarterkitsForbiddenCode is the HTTP code returned for type GetApisDevxIbmComV1alpha1StarterkitsForbidden
const GetApisDevxIbmComV1alpha1StarterkitsForbiddenCode int = 403

/*GetApisDevxIbmComV1alpha1StarterkitsForbidden Unauthorized

swagger:response getApisDevxIbmComV1alpha1StarterkitsForbidden
*/
type GetApisDevxIbmComV1alpha1StarterkitsForbidden struct {
}

// NewGetApisDevxIbmComV1alpha1StarterkitsForbidden creates GetApisDevxIbmComV1alpha1StarterkitsForbidden with default headers values
func NewGetApisDevxIbmComV1alpha1StarterkitsForbidden() *GetApisDevxIbmComV1alpha1StarterkitsForbidden {

	return &GetApisDevxIbmComV1alpha1StarterkitsForbidden{}
}

// WriteResponse to the client
func (o *GetApisDevxIbmComV1alpha1StarterkitsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
