// Code generated by go-swagger; DO NOT EDIT.

package starter_kit_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetApisDevxIbmComV1alpha1StarterkitsParams creates a new GetApisDevxIbmComV1alpha1StarterkitsParams object
// no default values defined in spec.
func NewGetApisDevxIbmComV1alpha1StarterkitsParams() GetApisDevxIbmComV1alpha1StarterkitsParams {

	return GetApisDevxIbmComV1alpha1StarterkitsParams{}
}

// GetApisDevxIbmComV1alpha1StarterkitsParams contains all the bound params for the get apis devx ibm com v1alpha1 starterkits operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetApisDevxIbmComV1alpha1Starterkits
type GetApisDevxIbmComV1alpha1StarterkitsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetApisDevxIbmComV1alpha1StarterkitsParams() beforehand.
func (o *GetApisDevxIbmComV1alpha1StarterkitsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
