// Code generated by go-swagger; DO NOT EDIT.

package starter_kit_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOKCode is the HTTP code returned for type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK
const GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOKCode int = 200

/*GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK OK

swagger:response getApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK
*/
type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK struct {
}

// NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK creates GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK with default headers values
func NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK() *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK {

	return &GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK{}
}

// WriteResponse to the client
func (o *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbiddenCode is the HTTP code returned for type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden
const GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbiddenCode int = 403

/*GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden Unauthorized

swagger:response getApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden
*/
type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden struct {
}

// NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden creates GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden with default headers values
func NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden() *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden {

	return &GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden{}
}

// WriteResponse to the client
func (o *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
