// Code generated by go-swagger; DO NOT EDIT.

package starter_kit_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsOKCode is the HTTP code returned for type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsOK
const GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsOKCode int = 200

/*GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsOK OK

swagger:response getApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsOK
*/
type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsOK struct {
}

// NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsOK creates GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsOK with default headers values
func NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsOK() *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsOK {

	return &GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsOK{}
}

// WriteResponse to the client
func (o *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsForbiddenCode is the HTTP code returned for type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsForbidden
const GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsForbiddenCode int = 403

/*GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsForbidden Unauthorized

swagger:response getApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsForbidden
*/
type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsForbidden struct {
}

// NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsForbidden creates GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsForbidden with default headers values
func NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsForbidden() *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsForbidden {

	return &GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsForbidden{}
}

// WriteResponse to the client
func (o *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
