// Code generated by go-swagger; DO NOT EDIT.

package starter_kit_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusHandlerFunc turns a function with the right signature into a get apis devx ibm com v1alpha1 namespaces namespace starterkits name status handler
type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusHandlerFunc func(GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusHandlerFunc) Handle(params GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusHandler interface for that can handle valid get apis devx ibm com v1alpha1 namespaces namespace starterkits name status params
type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusHandler interface {
	Handle(GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusParams, interface{}) middleware.Responder
}

// NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatus creates a new http.Handler for the get apis devx ibm com v1alpha1 namespaces namespace starterkits name status operation
func NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatus(ctx *middleware.Context, handler GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusHandler) *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatus {
	return &GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatus{Context: ctx, Handler: handler}
}

/*GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatus swagger:route GET /apis/devx.ibm.com/v1alpha1/namespaces/{namespace}/starterkits/{name}/status Starter Kit Operations getApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatus

read status of the specified StarterKit.

read status of the specified StarterKit.

*/
type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatus struct {
	Context *middleware.Context
	Handler GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusHandler
}

func (o *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
