// Code generated by go-swagger; DO NOT EDIT.

package starter_kit_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandlerFunc turns a function with the right signature into a get apis devx ibm com v1alpha1 namespaces namespace starterkits name handler
type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandlerFunc func(GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandlerFunc) Handle(params GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandler interface for that can handle valid get apis devx ibm com v1alpha1 namespaces namespace starterkits name params
type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandler interface {
	Handle(GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameParams, interface{}) middleware.Responder
}

// NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName creates a new http.Handler for the get apis devx ibm com v1alpha1 namespaces namespace starterkits name operation
func NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName(ctx *middleware.Context, handler GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandler) *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName {
	return &GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName{Context: ctx, Handler: handler}
}

/*GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName swagger:route GET /apis/devx.ibm.com/v1alpha1/namespaces/{namespace}/starterkits/{name} Starter Kit Operations getApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName

Returns starter kit information.

Returns details about a starter kit.

*/
type GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName struct {
	Context *middleware.Context
	Handler GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandler
}

func (o *GetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
