// Code generated by go-swagger; DO NOT EDIT.

package starter_kit_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetApisDevxIbmComV1alpha1StarterkitsHandlerFunc turns a function with the right signature into a get apis devx ibm com v1alpha1 starterkits handler
type GetApisDevxIbmComV1alpha1StarterkitsHandlerFunc func(GetApisDevxIbmComV1alpha1StarterkitsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetApisDevxIbmComV1alpha1StarterkitsHandlerFunc) Handle(params GetApisDevxIbmComV1alpha1StarterkitsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetApisDevxIbmComV1alpha1StarterkitsHandler interface for that can handle valid get apis devx ibm com v1alpha1 starterkits params
type GetApisDevxIbmComV1alpha1StarterkitsHandler interface {
	Handle(GetApisDevxIbmComV1alpha1StarterkitsParams, interface{}) middleware.Responder
}

// NewGetApisDevxIbmComV1alpha1Starterkits creates a new http.Handler for the get apis devx ibm com v1alpha1 starterkits operation
func NewGetApisDevxIbmComV1alpha1Starterkits(ctx *middleware.Context, handler GetApisDevxIbmComV1alpha1StarterkitsHandler) *GetApisDevxIbmComV1alpha1Starterkits {
	return &GetApisDevxIbmComV1alpha1Starterkits{Context: ctx, Handler: handler}
}

/*GetApisDevxIbmComV1alpha1Starterkits swagger:route GET /apis/devx.ibm.com/v1alpha1/starterkits Starter Kit Operations getApisDevxIbmComV1alpha1Starterkits

Return all starter kits located in all namespaces.

Returns a StarterKitList.

*/
type GetApisDevxIbmComV1alpha1Starterkits struct {
	Context *middleware.Context
	Handler GetApisDevxIbmComV1alpha1StarterkitsHandler
}

func (o *GetApisDevxIbmComV1alpha1Starterkits) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetApisDevxIbmComV1alpha1StarterkitsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
