// Code generated by go-swagger; DO NOT EDIT.

package starter_kit_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOKCode is the HTTP code returned for type PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK
const PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOKCode int = 200

/*PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK OK

swagger:response putApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK
*/
type PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK struct {
}

// NewPutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK creates PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK with default headers values
func NewPutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK() *PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK {

	return &PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK{}
}

// WriteResponse to the client
func (o *PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbiddenCode is the HTTP code returned for type PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden
const PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbiddenCode int = 403

/*PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden Unauthorized

swagger:response putApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden
*/
type PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden struct {
}

// NewPutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden creates PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden with default headers values
func NewPutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden() *PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden {

	return &PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden{}
}

// WriteResponse to the client
func (o *PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
