// Code generated by go-swagger; DO NOT EDIT.

package starter_kit_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandlerFunc turns a function with the right signature into a put apis devx ibm com v1alpha1 namespaces namespace starterkits name handler
type PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandlerFunc func(PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandlerFunc) Handle(params PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandler interface for that can handle valid put apis devx ibm com v1alpha1 namespaces namespace starterkits name params
type PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandler interface {
	Handle(PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameParams, interface{}) middleware.Responder
}

// NewPutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName creates a new http.Handler for the put apis devx ibm com v1alpha1 namespaces namespace starterkits name operation
func NewPutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName(ctx *middleware.Context, handler PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandler) *PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName {
	return &PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName{Context: ctx, Handler: handler}
}

/*PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName swagger:route PUT /apis/devx.ibm.com/v1alpha1/namespaces/{namespace}/starterkits/{name} Starter Kit Operations putApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName

Replace the specified StarterKit.

Replace the specified StarterKit.

*/
type PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName struct {
	Context *middleware.Context
	Handler PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameHandler
}

func (o *PutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutApisDevxIbmComV1alpha1NamespacesNamespaceStarterkitsNameParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
