// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Starter Kit Operator
//
//  Perform operations on Starter Kits.
//  Schemes:
//    https
//  Host: my-cluster-host
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/yaml
//
//  Produces:
//    - application/json
//    - application/vnd.kubernetes.protobuf
//    - application/yaml
//
// swagger:meta
package restapi
