// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Perform operations on Starter Kits.",
    "title": "Starter Kit Operator",
    "version": "1.0.0"
  },
  "host": "my-cluster-host",
  "paths": {
    "/api/v1/secrets?labelSelector=devx": {
      "get": {
        "description": "list or watch objects of kind Secret",
        "produces": [
          "application/json",
          "application/yaml",
          "application/vnd.kubernetes.protobuf",
          "application/json;stream=watch",
          "application/vnd.kubernetes.protobuf;stream=watch"
        ],
        "tags": [
          "core_v1"
        ],
        "summary": "list or watch objects of kind Secret",
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/apis/devx.ibm.com/v1alpha1/namespaces/{namespace}/starterkits": {
      "get": {
        "description": "Returns a StarterKitList.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Starter Kit Operations"
        ],
        "summary": "Return all installed starter kits located in a specific namespace.",
        "parameters": [
          {
            "type": "string",
            "description": "Namespace where the starter kit is located.",
            "name": "namespace",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "post": {
        "consumes": [
          "application/yaml"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Starter Kit Operations"
        ],
        "summary": "Creates a starter kit.",
        "parameters": [
          {
            "type": "string",
            "description": "Namespace where the starter kit will be located.",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "description": "Stringified yaml matching starter kit kind.",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/apis/devx.ibm.com/v1alpha1/namespaces/{namespace}/starterkits/{name}": {
      "get": {
        "description": "Returns details about a starter kit.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Starter Kit Operations"
        ],
        "summary": "Returns starter kit information.",
        "parameters": [
          {
            "type": "string",
            "description": "Namespace where the starter kit is located.",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the starter kit.",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "put": {
        "description": "Replace the specified StarterKit.",
        "produces": [
          "application/json",
          "application/yaml"
        ],
        "tags": [
          "Starter Kit Operations"
        ],
        "summary": "Replace the specified StarterKit.",
        "parameters": [
          {
            "type": "string",
            "description": "Namespace where the starter kit is located.",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the starter kit.",
            "name": "name",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/apis/devx.ibm.com/v1alpha1/namespaces/{namespace}/starterkits/{name}/status": {
      "get": {
        "description": "read status of the specified StarterKit.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Starter Kit Operations"
        ],
        "summary": "read status of the specified StarterKit.",
        "parameters": [
          {
            "type": "string",
            "description": "Namespace where the starter kit is located.",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the starter kit.",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/apis/devx.ibm.com/v1alpha1/starterkits": {
      "get": {
        "description": "Returns a StarterKitList.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Starter Kit Operations"
        ],
        "summary": "Return all starter kits located in all namespaces.",
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "Bearer": []
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Perform operations on Starter Kits.",
    "title": "Starter Kit Operator",
    "version": "1.0.0"
  },
  "host": "my-cluster-host",
  "paths": {
    "/api/v1/secrets?labelSelector=devx": {
      "get": {
        "description": "list or watch objects of kind Secret",
        "produces": [
          "application/json",
          "application/json;stream=watch",
          "application/vnd.kubernetes.protobuf",
          "application/vnd.kubernetes.protobuf;stream=watch",
          "application/yaml"
        ],
        "tags": [
          "core_v1"
        ],
        "summary": "list or watch objects of kind Secret",
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/apis/devx.ibm.com/v1alpha1/namespaces/{namespace}/starterkits": {
      "get": {
        "description": "Returns a StarterKitList.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Starter Kit Operations"
        ],
        "summary": "Return all installed starter kits located in a specific namespace.",
        "parameters": [
          {
            "type": "string",
            "description": "Namespace where the starter kit is located.",
            "name": "namespace",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "post": {
        "consumes": [
          "application/yaml"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Starter Kit Operations"
        ],
        "summary": "Creates a starter kit.",
        "parameters": [
          {
            "type": "string",
            "description": "Namespace where the starter kit will be located.",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "description": "Stringified yaml matching starter kit kind.",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/apis/devx.ibm.com/v1alpha1/namespaces/{namespace}/starterkits/{name}": {
      "get": {
        "description": "Returns details about a starter kit.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Starter Kit Operations"
        ],
        "summary": "Returns starter kit information.",
        "parameters": [
          {
            "type": "string",
            "description": "Namespace where the starter kit is located.",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the starter kit.",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "put": {
        "description": "Replace the specified StarterKit.",
        "produces": [
          "application/json",
          "application/yaml"
        ],
        "tags": [
          "Starter Kit Operations"
        ],
        "summary": "Replace the specified StarterKit.",
        "parameters": [
          {
            "type": "string",
            "description": "Namespace where the starter kit is located.",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the starter kit.",
            "name": "name",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/apis/devx.ibm.com/v1alpha1/namespaces/{namespace}/starterkits/{name}/status": {
      "get": {
        "description": "read status of the specified StarterKit.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Starter Kit Operations"
        ],
        "summary": "read status of the specified StarterKit.",
        "parameters": [
          {
            "type": "string",
            "description": "Namespace where the starter kit is located.",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the starter kit.",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/apis/devx.ibm.com/v1alpha1/starterkits": {
      "get": {
        "description": "Returns a StarterKitList.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Starter Kit Operations"
        ],
        "summary": "Return all starter kits located in all namespaces.",
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "Bearer": []
    }
  ]
}`))
}
